---

- name: Get token from master
  delegate_to: '{{ kubernetes_master_ip }}'
  shell: |
    /usr/bin/kubeadm token create
  register: kubernetes_token
  when: kubernetes_token is not defined

- set_fact:
    kubernetes_token: '{{ kubernetes_token.stdout }}'

- name: Join node
  shell: |
    /usr/bin/kubeadm join --token {{ kubernetes_token }} {{ kubernetes_master_ip }}:{{ kubernetes_port }} --discovery-token-unsafe-skip-ca-verification
  args:
    creates: /etc/kubernetes/bootstrap-kubelet.conf

